"""Sends a summary notification to a Microsoft Teams channel after the
live CI run, using the results.json already generated by the workflow."""

import json
import os
import urllib.request

WEBHOOK_URL = os.environ["TEAMS_WEBHOOK_URL"]
RUN_URL = f"{os.environ['GITHUB_SERVER_URL']}/{os.environ['GITHUB_REPOSITORY']}/actions/runs/{os.environ['GITHUB_RUN_ID']}"


def main():
    with open("results.json", "r", encoding="utf-8") as f:
        results = json.load(f)

    total = results["total"]
    passed = results["passed"]
    failed = results["failed"]
    pass_rate = round((passed / total) * 100, 1) if total else 0

    theme_color = "2EB67D" if failed == 0 else "E01E5A"
    status_emoji = "🟢" if failed == 0 else "🔴"

    payload = {
        "@type": "MessageCard",
        "@context": "http://schema.org/extensions",
        "summary": f"CI (live) results for {results['repo']}",
        "themeColor": theme_color,
        "title": f"{status_emoji} {results['repo']} - CI (live) result",
        "sections": [
            {
                "facts": [
                    {"name": "Total", "value": str(total)},
                    {"name": "Passed", "value": str(passed)},
                    {"name": "Failed", "value": str(failed)},
                    {"name": "Pass rate", "value": f"{pass_rate}%"},
                ],
                "text": "This run called the real OpenAI API. See the full run for logs and downloadable artifacts.",
            }
        ],
        "potentialAction": [
            {
                "@type": "OpenUri",
                "name": "View CI run",
                "targets": [{"os": "default", "uri": RUN_URL}],
            }
        ],
    }

    request = urllib.request.Request(
        WEBHOOK_URL,
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
    )
    with urllib.request.urlopen(request) as response:
        print(f"Teams notification sent, status: {response.status}")


if __name__ == "__main__":
    main()